# Generated by Django 4.1.1 on 2023-04-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='phonenumber',
            field=models.BigIntegerField(default=0),
        ),
    ]
