# Generated by Django 4.1.1 on 2022-10-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('book_quantity', models.BigIntegerField(default=0)),
                ('book_price', models.BigIntegerField(default=0)),
                ('book_oldprice', models.BigIntegerField(default=0)),
                ('book_author', models.CharField(max_length=50)),
                ('book_year', models.BigIntegerField(default=0)),
                ('book_language', models.CharField(max_length=50)),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_status', models.BooleanField(default=True)),
                ('book_desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(default=0, upload_to='pics')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homeapp.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('book_name',),
            },
        ),
    ]
