# Generated by Django 4.1.1 on 2023-02-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_booktypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='eBooks',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('ebook_name', models.CharField(max_length=100)),
                ('book_price', models.BigIntegerField(default=0)),
                ('book_oldprice', models.BigIntegerField(default=0)),
                ('book_author', models.CharField(max_length=50)),
                ('book_year', models.BigIntegerField(default=0)),
                ('book_language', models.CharField(max_length=50)),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_status', models.BooleanField(default=True)),
                ('book_desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(default=0, upload_to='pics')),
                ('listening_length', models.DurationField(blank=True, default='00:00:00', null=True)),
                ('narrator', models.CharField(blank=True, max_length=50, null=True)),
                ('audibleRelease_date', models.DateTimeField(auto_now_add=True)),
                ('book_audioFile', models.FileField(blank=True, null=True, upload_to='AudioFiles')),
                ('book_pdf', models.FileField(blank=True, null=True, upload_to='PdfFiles')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homeapp.category', verbose_name='Category')),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homeapp.booktypes', verbose_name='BookType')),
            ],
        ),
    ]
