# Generated by Django 4.1.1 on 2023-02-28 06:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='book_audioFile',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\jesna\\OneDrive\\Documents\\Bookstore-C\\BookStore\\bookstore\\media\\audio'), upload_to=''),
        ),
    ]
