# Generated by Django 4.1.1 on 2023-03-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_ebooks_book_flipbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='book_flipbook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
