# Generated by Django 4.1.1 on 2023-03-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_alter_ebooks_book_flipbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
