# Generated by Django 4.1.1 on 2023-03-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_alter_ebooks_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
