# Generated by Django 4.1.1 on 2023-03-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0018_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
