# Generated by Django 4.1.1 on 2023-05-01 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0007_address_last_name'),
        ('homeapp', '0020_orderplaced_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='customer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logapp.address'),
        ),
    ]
